name: client-ci
on:
  push:
    paths: ["client/**", ".github/workflows/client-ci.yml"]
  pull_request:
    paths: ["client/**"]
jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet build ./client/ScreenTime/ScreenTime.csproj
      - run: dotnet test ./client/ScreenTime.Tests/ScreenTime.Tests.csproj
